services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tpch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  populator:
    build:
      context: .
      dockerfile: Dockerfile.populator
    depends_on:
      - db 
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/tpch"

volumes:
  postgres_data:

